# Generated by Django 4.2.9 on 2024-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_alter_user_status_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('book_author', models.CharField(max_length=150)),
                ('book_quantity', models.IntegerField()),
                ('book_description', models.TextField()),
                ('borrowed_user', models.CharField(blank=True, max_length=20, null=True)),
                ('borrowed_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
